server:
  port: ${port:9002 }

spring:
  profiles:
    include: mysql,redis


security:
  oauth2:
    accessTokenValiditySeconds: ${access-token-validity-seconds:1800} # 令牌过期时间 半个小时
    refreshTokenValiditySeconds: ${refresh-token-validity-seconds:3600} # 令牌刷新有限时间
    client-id: ${client-id:yangsensen-created-oauth-service}
    secret: ${client-secret:hkjhflkdsdf}
    authorizedGrantTypes:
      - password
      - refresh_token
    scopes:
      - all
    accessTokenUri: http://${access-token-ip:127.0.0.1}:${server.port}/oauth/token
