server:
  port: 9003

spring:
  application:
    name: cad-web
  profiles:
    include: redis,drill,common,swagger
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

storage:
  cacheStorage: redis
  fileStorage: local
  expired: 604800 # 单位s, 这里设置过期时间为7天