spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/databasebykg
    username: yangsensen
    password: Rty2CksFuMnnTPNv
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 1